/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandleGoogleAuthorizationCodeCommand,
  HandleGoogleLoginCommand,
  HandleGoogleRefreshTokenCommand,
  UserVm,
} from '../models';
import {
    HandleGoogleAuthorizationCodeCommandFromJSON,
    HandleGoogleAuthorizationCodeCommandToJSON,
    HandleGoogleLoginCommandFromJSON,
    HandleGoogleLoginCommandToJSON,
    HandleGoogleRefreshTokenCommandFromJSON,
    HandleGoogleRefreshTokenCommandToJSON,
    UserVmFromJSON,
    UserVmToJSON,
} from '../models';

export interface AuthGoogleAuthRequest {
    handleGoogleLoginCommand: HandleGoogleLoginCommand;
}

export interface AuthGoogleAuthCodeRequest {
    handleGoogleAuthorizationCodeCommand: HandleGoogleAuthorizationCodeCommand;
}

export interface AuthGoogleRefreshRequest {
    handleGoogleRefreshTokenCommand: HandleGoogleRefreshTokenCommand;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authGoogleAuthRaw(requestParameters: AuthGoogleAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserVm>> {
        if (requestParameters.handleGoogleLoginCommand === null || requestParameters.handleGoogleLoginCommand === undefined) {
            throw new runtime.RequiredError('handleGoogleLoginCommand','Required parameter requestParameters.handleGoogleLoginCommand was null or undefined when calling authGoogleAuth.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // JWT authentication
        }

        const response = await this.request({
            path: `/api/Auth/google`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandleGoogleLoginCommandToJSON(requestParameters.handleGoogleLoginCommand),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserVmFromJSON(jsonValue));
    }

    /**
     */
    async authGoogleAuth(requestParameters: AuthGoogleAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserVm> {
        const response = await this.authGoogleAuthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authGoogleAuthCodeRaw(requestParameters: AuthGoogleAuthCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserVm>> {
        if (requestParameters.handleGoogleAuthorizationCodeCommand === null || requestParameters.handleGoogleAuthorizationCodeCommand === undefined) {
            throw new runtime.RequiredError('handleGoogleAuthorizationCodeCommand','Required parameter requestParameters.handleGoogleAuthorizationCodeCommand was null or undefined when calling authGoogleAuthCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // JWT authentication
        }

        const response = await this.request({
            path: `/api/Auth/google-auth-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandleGoogleAuthorizationCodeCommandToJSON(requestParameters.handleGoogleAuthorizationCodeCommand),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserVmFromJSON(jsonValue));
    }

    /**
     */
    async authGoogleAuthCode(requestParameters: AuthGoogleAuthCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserVm> {
        const response = await this.authGoogleAuthCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authGoogleRefreshRaw(requestParameters: AuthGoogleRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserVm>> {
        if (requestParameters.handleGoogleRefreshTokenCommand === null || requestParameters.handleGoogleRefreshTokenCommand === undefined) {
            throw new runtime.RequiredError('handleGoogleRefreshTokenCommand','Required parameter requestParameters.handleGoogleRefreshTokenCommand was null or undefined when calling authGoogleRefresh.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // JWT authentication
        }

        const response = await this.request({
            path: `/api/Auth/google-refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandleGoogleRefreshTokenCommandToJSON(requestParameters.handleGoogleRefreshTokenCommand),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserVmFromJSON(jsonValue));
    }

    /**
     */
    async authGoogleRefresh(requestParameters: AuthGoogleRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserVm> {
        const response = await this.authGoogleRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
