/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BarCharDataSet
 */
export interface BarCharDataSet {
    /**
     * 
     * @type {string}
     * @memberof BarCharDataSet
     */
    label: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof BarCharDataSet
     */
    values: Array<number>;
}

/**
 * Check if a given object implements the BarCharDataSet interface.
 */
export function instanceOfBarCharDataSet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "values" in value;

    return isInstance;
}

export function BarCharDataSetFromJSON(json: any): BarCharDataSet {
    return BarCharDataSetFromJSONTyped(json, false);
}

export function BarCharDataSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BarCharDataSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'values': json['values'],
    };
}

export function BarCharDataSetToJSON(value?: BarCharDataSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'values': value.values,
    };
}

