/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BarChartRow
 */
export interface BarChartRow {
    /**
     * 
     * @type {string}
     * @memberof BarChartRow
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof BarChartRow
     */
    identifier: number;
    /**
     * 
     * @type {number}
     * @memberof BarChartRow
     */
    value: number;
}

/**
 * Check if a given object implements the BarChartRow interface.
 */
export function instanceOfBarChartRow(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function BarChartRowFromJSON(json: any): BarChartRow {
    return BarChartRowFromJSONTyped(json, false);
}

export function BarChartRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): BarChartRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'identifier': json['identifier'],
        'value': json['value'],
    };
}

export function BarChartRowToJSON(value?: BarChartRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'identifier': value.identifier,
        'value': value.value,
    };
}

