/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IrcChannelDto } from './IrcChannelDto';
import {
    IrcChannelDtoFromJSON,
    IrcChannelDtoFromJSONTyped,
    IrcChannelDtoToJSON,
} from './IrcChannelDto';

/**
 * 
 * @export
 * @interface GetIrcChannelsVm
 */
export interface GetIrcChannelsVm {
    /**
     * 
     * @type {Array<IrcChannelDto>}
     * @memberof GetIrcChannelsVm
     */
    channels?: Array<IrcChannelDto>;
}

/**
 * Check if a given object implements the GetIrcChannelsVm interface.
 */
export function instanceOfGetIrcChannelsVm(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetIrcChannelsVmFromJSON(json: any): GetIrcChannelsVm {
    return GetIrcChannelsVmFromJSONTyped(json, false);
}

export function GetIrcChannelsVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIrcChannelsVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channels': !exists(json, 'channels') ? undefined : ((json['channels'] as Array<any>).map(IrcChannelDtoFromJSON)),
    };
}

export function GetIrcChannelsVmToJSON(value?: GetIrcChannelsVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channels': value.channels === undefined ? undefined : ((value.channels as Array<any>).map(IrcChannelDtoToJSON)),
    };
}

