/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IrcRowDto } from './IrcRowDto';
import {
    IrcRowDtoFromJSON,
    IrcRowDtoFromJSONTyped,
    IrcRowDtoToJSON,
} from './IrcRowDto';

/**
 * 
 * @export
 * @interface GetIrcRowsVm
 */
export interface GetIrcRowsVm {
    /**
     * 
     * @type {Array<IrcRowDto>}
     * @memberof GetIrcRowsVm
     */
    rows: Array<IrcRowDto>;
}

/**
 * Check if a given object implements the GetIrcRowsVm interface.
 */
export function instanceOfGetIrcRowsVm(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rows" in value;

    return isInstance;
}

export function GetIrcRowsVmFromJSON(json: any): GetIrcRowsVm {
    return GetIrcRowsVmFromJSONTyped(json, false);
}

export function GetIrcRowsVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIrcRowsVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rows': ((json['rows'] as Array<any>).map(IrcRowDtoFromJSON)),
    };
}

export function GetIrcRowsVmToJSON(value?: GetIrcRowsVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rows': ((value.rows as Array<any>).map(IrcRowDtoToJSON)),
    };
}

