/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleGoogleLoginCommand
 */
export interface HandleGoogleLoginCommand {
    /**
     * 
     * @type {string}
     * @memberof HandleGoogleLoginCommand
     */
    tokenId?: string;
}

/**
 * Check if a given object implements the HandleGoogleLoginCommand interface.
 */
export function instanceOfHandleGoogleLoginCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HandleGoogleLoginCommandFromJSON(json: any): HandleGoogleLoginCommand {
    return HandleGoogleLoginCommandFromJSONTyped(json, false);
}

export function HandleGoogleLoginCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleGoogleLoginCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenId': !exists(json, 'tokenId') ? undefined : json['tokenId'],
    };
}

export function HandleGoogleLoginCommandToJSON(value?: HandleGoogleLoginCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenId': value.tokenId,
    };
}

