/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleGoogleRefreshTokenCommand
 */
export interface HandleGoogleRefreshTokenCommand {
    /**
     * 
     * @type {string}
     * @memberof HandleGoogleRefreshTokenCommand
     */
    email?: string;
}

/**
 * Check if a given object implements the HandleGoogleRefreshTokenCommand interface.
 */
export function instanceOfHandleGoogleRefreshTokenCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HandleGoogleRefreshTokenCommandFromJSON(json: any): HandleGoogleRefreshTokenCommand {
    return HandleGoogleRefreshTokenCommandFromJSONTyped(json, false);
}

export function HandleGoogleRefreshTokenCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleGoogleRefreshTokenCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function HandleGoogleRefreshTokenCommandToJSON(value?: HandleGoogleRefreshTokenCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

