/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleGoogleAuthorizationCodeCommand
 */
export interface HandleGoogleAuthorizationCodeCommand {
    /**
     * 
     * @type {string}
     * @memberof HandleGoogleAuthorizationCodeCommand
     */
    authorizationCode?: string;
    /**
     * 
     * @type {string}
     * @memberof HandleGoogleAuthorizationCodeCommand
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HandleGoogleAuthorizationCodeCommand
     */
    isRefresh?: boolean;
}

/**
 * Check if a given object implements the HandleGoogleAuthorizationCodeCommand interface.
 */
export function instanceOfHandleGoogleAuthorizationCodeCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HandleGoogleAuthorizationCodeCommandFromJSON(json: any): HandleGoogleAuthorizationCodeCommand {
    return HandleGoogleAuthorizationCodeCommandFromJSONTyped(json, false);
}

export function HandleGoogleAuthorizationCodeCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleGoogleAuthorizationCodeCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizationCode': !exists(json, 'authorizationCode') ? undefined : json['authorizationCode'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'isRefresh': !exists(json, 'isRefresh') ? undefined : json['isRefresh'],
    };
}

export function HandleGoogleAuthorizationCodeCommandToJSON(value?: HandleGoogleAuthorizationCodeCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorizationCode': value.authorizationCode,
        'email': value.email,
        'isRefresh': value.isRefresh,
    };
}

