/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IrcRowDto
 */
export interface IrcRowDto {
    /**
     * 
     * @type {number}
     * @memberof IrcRowDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IrcRowDto
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof IrcRowDto
     */
    nick?: string;
    /**
     * 
     * @type {string}
     * @memberof IrcRowDto
     */
    channel?: string;
    /**
     * 
     * @type {Date}
     * @memberof IrcRowDto
     */
    timeStamp?: Date;
}

/**
 * Check if a given object implements the IrcRowDto interface.
 */
export function instanceOfIrcRowDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IrcRowDtoFromJSON(json: any): IrcRowDto {
    return IrcRowDtoFromJSONTyped(json, false);
}

export function IrcRowDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IrcRowDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'nick': !exists(json, 'nick') ? undefined : json['nick'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'timeStamp': !exists(json, 'timeStamp') ? undefined : (new Date(json['timeStamp'])),
    };
}

export function IrcRowDtoToJSON(value?: IrcRowDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'message': value.message,
        'nick': value.nick,
        'channel': value.channel,
        'timeStamp': value.timeStamp === undefined ? undefined : (value.timeStamp.toISOString()),
    };
}

