/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverviewStatisticsVmAllOf
 */
export interface OverviewStatisticsVmAllOf {
    /**
     * 
     * @type {string}
     * @memberof OverviewStatisticsVmAllOf
     */
    channelName: string;
}

/**
 * Check if a given object implements the OverviewStatisticsVmAllOf interface.
 */
export function instanceOfOverviewStatisticsVmAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelName" in value;

    return isInstance;
}

export function OverviewStatisticsVmAllOfFromJSON(json: any): OverviewStatisticsVmAllOf {
    return OverviewStatisticsVmAllOfFromJSONTyped(json, false);
}

export function OverviewStatisticsVmAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewStatisticsVmAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelName': json['channelName'],
    };
}

export function OverviewStatisticsVmAllOfToJSON(value?: OverviewStatisticsVmAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelName': value.channelName,
    };
}

