/* tslint:disable */
/* eslint-disable */
/**
 * IrcMonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BarChartReturnModel } from './BarChartReturnModel';
import {
    BarChartReturnModelFromJSON,
    BarChartReturnModelFromJSONTyped,
    BarChartReturnModelToJSON,
} from './BarChartReturnModel';

/**
 * 
 * @export
 * @interface YearlyStatisticsVm
 */
export interface YearlyStatisticsVm {
    /**
     * 
     * @type {BarChartReturnModel}
     * @memberof YearlyStatisticsVm
     */
    rows: BarChartReturnModel;
    /**
     * 
     * @type {string}
     * @memberof YearlyStatisticsVm
     */
    channelId: string;
    /**
     * 
     * @type {number}
     * @memberof YearlyStatisticsVm
     */
    year?: number | null;
    /**
     * 
     * @type {string}
     * @memberof YearlyStatisticsVm
     */
    channel?: string;
}

/**
 * Check if a given object implements the YearlyStatisticsVm interface.
 */
export function instanceOfYearlyStatisticsVm(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rows" in value;
    isInstance = isInstance && "channelId" in value;

    return isInstance;
}

export function YearlyStatisticsVmFromJSON(json: any): YearlyStatisticsVm {
    return YearlyStatisticsVmFromJSONTyped(json, false);
}

export function YearlyStatisticsVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): YearlyStatisticsVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rows': BarChartReturnModelFromJSON(json['rows']),
        'channelId': json['channelId'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
    };
}

export function YearlyStatisticsVmToJSON(value?: YearlyStatisticsVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rows': BarChartReturnModelToJSON(value.rows),
        'channelId': value.channelId,
        'year': value.year,
        'channel': value.channel,
    };
}

