# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - IrcMonitor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Setup .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Install LocalDB
      - name: Install LocalDB
        uses: potatoqualitee/mssqlsuite@v1.8
        with:
          install: localdb

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build test projects
        run: |
          dotnet build tests/Application.IntegrationTests/Application.IntegrationTests.csproj  --configuration Release
          dotnet build tests/Application.UnitTests/Application.UnitTests.csproj  --configuration Release

      - name: Test with the dotnet CLI
        run: |
          dotnet test tests/Application.IntegrationTests/Application.IntegrationTests.csproj
          dotnet test tests/Application.UnitTests/Application.UnitTests.csproj

      # Install deps
      - name: Install dependencies for React UI
        run: yarn install --cwd src/IrcMonitor.ReactUi

      # Build React UI
      - name: Build React UI
        env:
          REACT_APP_GOOGLE_APP_ID: ${{ secrets.GOOGLEAPPID }}
        run: |
          cd src/IrcMonitor.ReactUi
          yarn build

      # Copy React build output to .NET's wwwroot
      - name: Copy React build to .NET wwwroot
        run: |
          cp -r src/IrcMonitor.ReactUi/build/* src/IrcMonitor.WebUI/wwwroot/

      - name: dotnet publish
        run: dotnet publish src/IrcMonitor.WebUI/IrcMonitor.WebUI.csproj  -c Release -o "${{env.DOTNET_ROOT}}/irc-monitor"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/irc-monitor

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "IrcMonitor"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C18A791C34E945EB9FB49AFB6EE88B78 }}
          package: .
